### ISSUE TITLE
Nuxt 3 の対応( parser 設定のアプデ )

### ISSUE THREAD

**Issue by huequica** [node-jeneralize/pkfire#213]
# summary

- Nuxt3 からプロジェクトを `nuxi init` で作った場合 ESLint などが完全に同梱されなくなった
  - 今後変わる可能性あり
- それはそれとして設定が初期状態だと動かない問題が見られたので設定の変更を入れる

```
# .eslintrc.yaml
root: true
env:
  es6: true
  node: true
  browser: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:nuxt/recommended
  - "@nuxtjs/eslint-config-typescript"
  - prettier
plugins:
  - "@typescript-eslint"
parserOptions:
  # ここに居ないと defineComponent の ParseError が出る
  parser: "@typescript-eslint/parser"

rules:
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': error
```
